# Generated by Django 5.0 on 2023-12-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomarket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
    ]
