# Generated by Django 5.0 on 2024-01-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomarket', '0002_remove_cartitem_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='info/', verbose_name='Изображения')),
                ('text', models.TextField()),
                ('whatsapp_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('inst_contact', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
